# Load data

activity_data <- read.csv('./activity.csv')
activity_data$date <- as.Date(activity_data$date)
activity_data$interval <- as.factor(activity_data$interval)
names(activity_data)
lapply(activity_data, class)

# What is mean total number of steps taken per day?
library(plyr)
analysis_1_data <- ddply(activity_data[,1:2], .(date), function(set) { sum(set$steps, na.rm = TRUE) })
names(analysis_1_data) <- c("date", "steps")
library(ggplot2)
ggplot(data = analysis_1_data) + aes(x = factor(date), y = steps) + geom_histogram(stat = "identity") + labs(x ="Date", y = "Total number of steps") + theme(axis.text.x=element_text(angle = -90, hjust = 0))
mean(analysis_1_data$steps)
median(analysis_1_data$steps)

# What is the average daily activity pattern?
analysis_2_data <- ddply(activity_data, .(interval), function(set) { mean(set$steps, na.rm = TRUE) })
names(analysis_2_data) <- c("interval", "steps")
hour_intervals <- c(12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 156, 168, 180, 192, 204, 216, 228, 240, 252, 264, 276)
ggplot(data = analysis_2_data) + aes(x = factor(interval), y = steps, group = 1) + geom_line() + labs(x ="5-minute interval", y = "Average number of steps across all days") + theme(axis.text.x = element_text(size = 0)) + geom_vline(xintercept= hour_intervals, linetype="dotted") + geom_vline(xintercept= 144, colour = "red") + geom_text(x=144, y = 150, label="12 pm", angle = 90)
analysis_2_data[analysis_2_data$steps == max(analysis_2_data$steps), ]$interval

# Input Missing Values
nrow(activity_data[is.na(activity_data$steps), ])
impute_mean <- function(x) {
 replace(x, is.na(x), mean(x, na.rm = TRUE))
}
activity_data$order <- 1:nrow(activity_data)
imputed_activity_data <- ddply(activity_data, .(interval), transform, steps = impute_mean(steps))
imputed_activity_data <- imputed_activity_data[order(imputed_activity_data$order), ]
names(activity_data)
lapply(activity_data, class)
analysis_3_data <- ddply(imputed_activity_data[,1:2], .(date), function(set) { sum(set$steps, na.rm = TRUE) })
names(analysis_3_data) <- c("date", "steps")
ggplot(data = analysis_3_data) + aes(x = factor(date), y = steps) + geom_histogram(stat = "identity") + labs(x ="Date", y = "Total number of steps (NA imputed)") + theme(axis.text.x=element_text(angle = -90, hjust = 0))
mean(analysis_3_data$steps)
median(analysis_3_data$steps)


# Are there differences in activity patterns between weekdays and weekends?

which_day <- weekdays(imputed_activity_data$date)
imputed_activity_data$which_day <- ifelse(which_day == "Saturday" | which_day == "Sunday" , c("weekend"), c("weekday"))
imputed_activity_data$which_day <- factor(imputed_activity_data$which_day)
names(imputed_activity_data)
lapply(imputed_activity_data, class)
analysis_4_data_weekdays <- ddply(imputed_activity_data[imputed_activity_data$which_day == "weekday", ], .(interval), function(set) { mean(set$steps, na.rm = TRUE) })
names(analysis_4_data_weekdays) <- c("interval", "steps")
analysis_4_data_weekends <- ddply(imputed_activity_data[imputed_activity_data$which_day == "weekend", ], .(interval), function(set) { mean(set$steps, na.rm = TRUE) })
names(analysis_4_data_weekends) <- c("interval", "steps")
plot_weekdays <- ggplot(data = analysis_4_data_weekdays) + aes(x = factor(interval), y = steps, group = 1) + geom_line() + labs(x ="5-minute interval", y = "Average number of steps across weekdays") + theme(axis.text.x = element_text(size = 0)) + geom_vline(xintercept= hour_intervals, linetype="dotted") + geom_vline(xintercept= 144, colour = "red") + geom_text(x=144, y = 150, label="12 pm", angle = 90)
plot_weekends <- ggplot(data = analysis_4_data_weekends) + aes(x = factor(interval), y = steps, group = 1) + geom_line() + labs(x ="5-minute interval", y = "Average number of steps across weekends") + theme(axis.text.x = element_text(size = 0)) + geom_vline(xintercept= hour_intervals, linetype="dotted") + geom_vline(xintercept= 144, colour = "red") + geom_text(x=144, y = 150, label="12 pm", angle = 90)

multiplot <- function(..., plotlist=NULL, cols) {
require(grid)  
plots <- c(list(...), plotlist)
numPlots = length(plots)
plotCols = cols                          
plotRows = ceiling(numPlots/plotCols)
grid.newpage()
pushViewport(viewport(layout = grid.layout(plotRows, plotCols)))
vplayout <- function(x, y)
viewport(layout.pos.row = x, layout.pos.col = y)
for (i in 1:numPlots) {
    	curRow = ceiling(i/plotCols)
    	curCol = (i-1) %% plotCols + 1
    	print(plots[[i]], vp = vplayout(curRow, curCol ))
  	}
 }

multiplot(plot_weekdays, plot_weekends, cols = 1)
